version: '3'

services:
  web:
    build: .
    command: gunicorn mypy.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes: 
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django_app
      - POSTGRES_DB=django
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  redis:
    image: redis:latest
    environment:
      - REDIS_USER=cache
      - REDIS_PASSWORD=cache_cache
    expose:
      - 6379
    depends_on:
      - web

volumes:
  pgdata: