#NO LONGER IN USE

version: '3'

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:1234"
    volumes:
      - .:/dsh/
    ports:
      - 1234:1234
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes: 
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django_app
      - POSTGRES_DB=django

volumes:
  pgdata: